name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 ssh.cg7zrcp0z.service.one >> ~/.ssh/known_hosts

      - name: Deploy to sandernilsen.no
        run: |
          rsync -avz \
            --exclude ".git*" \
            --exclude ".github" \
            --exclude "README.md" \
            -e "ssh -p 22" \
            ./ cg7zrcp0z_h5343026@ssh.cg7zrcp0z.service.one:/run/webroots/by-route/sandernilsen.no_/

      - name: Deploy to www.sandernilsen.no
        run: |
          rsync -avz \
            --exclude ".git*" \
            --exclude ".github" \
            --exclude "README.md" \
            -e "ssh -p 22" \
            ./ cg7zrcp0z_h5343026@ssh.cg7zrcp0z.service.one:/run/webroots/by-route/www.sandernilsen.no_/